name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.2'
    - uses: actions/checkout@v4
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Run PHP_CodeSniffer (lint)
      run: vendor/bin/phpcs --standard=PSR12 app/ routes/ tests/
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Parent Directories
      run: mkdir -p /var/www
    - name: Create Database Manually
      run: |
        mkdir -p /var/www/database
        touch /var/www/database/database.sqlite
        chmod -R 777 /var/www/database
    - name: Verify Database File
      run: ls -l /var/www/database/database.sqlite
    - name: Run Migrations
      run: php artisan migrate --force
    - name: Seed Database
      run: php artisan db:seed --force
    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test
    - name: Docker login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Build Docker image
      run: docker build -t illunatie/laravel-app:latest .
    - name: Push image to Docker Hub
      run: docker push illunatie/laravel-app:latest

